### PR TITLE
[feature] SVG Data URL

### PR DESCRIPTION
**Pull request by kriserickson**
Allows for uploading SVG images and converting them to dataUrls that aren't base64 encoded (https://css-tricks.com/probably-dont-base64-svg/)

### CODE REVIEW

**Comment by inssein** [comment]
Damn sorry @kriserickson but this PR is probably going to have to change a bunch after the image convert stuff merges.

**Comment by kriserickson** [comment]
> Damn sorry @kriserickson but this PR is probably going to have to change a bunch after the image convert stuff merges.

Yup.  Probably be only a few minutes to rewrite though.

**Comment by inssein** [comment]
Okay so I am happy to merge now, but here are some thoughts that I don't know what to do about right now:

- When you drag and drop a file you can drop a file with any extension, which kind of still works but if it's not an image, the preview breaks.
- Annoying that you must select the right type before you drag and drop. Worse than the image converter because if you change type, you have to drop file again. There is no real way around this because a user can also paste and then edit contents, so saving the file reference alone will just be as broken of an experience.

**Review by inssein — APPROVED** [review]

**Comment by inssein** [comment]
@kriserickson approving it so feel free to merge, but let me know if you have thoughts on my comments.

**Pull request merged**
